# Generated by Django 5.2 on 2025-10-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0002_student_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
