# Generated by Django 5.2 on 2025-10-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0003_notice"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="notices/"),
        ),
    ]
